baseURL: "https://www.pybamm.org"
languageCode: "en-us"
title: "PyBaMM" # site title
theme: scientific-python-hugo-theme
relativeURLs: true
DefaultContentLanguage: en
disableKinds: ["term", "taxonomy"]
enableEmoji: true
enableInlineShortcodes: true

markup:
  highlight:
    noClasses: true
    style: github-dark
  goldmark:
    renderer:
      unsafe: true

params:
  title: PyBaMM website
  description: "PyBaMM (Python Battery Mathematical Modelling) is an open-source battery simulation package written in Python."
  author:
    name: PyBaMM Team
  # Privacy-preserving analytics
  plausible:
    dataDomain: pybamm.org
    javaScript: https://plausible.io/js/script.js

  images:
    - /images/pybamm_icon.png

  font:
    name: "Lato"
    sizes: [400, 900]

  style:
    vars:
      highlightColor: "#004811"
      menuHighlightColor: "#5CA038"

  navbarlogo:
    image: pybamm_icon.svg
    altText: The PyBaMM logo, with a battery of cells with the electrodes stacked in the standard Python blue and yellow colours
    text: PyBaMM
    link: /

  hero:
    title: PyBaMM
    subtitle: Fast and flexible physics-based battery models in Python
    buttontext: View releases
    buttonlink: https://github.com/pybamm-team/PyBaMM/releases
    image: pybamm_icon.svg

  navbar:
    - title: Install
      url: https://docs.pybamm.org/en/stable/source/user_guide/installation/index.html
      is_external: true

    - title: Documentation
      url: https://docs.pybamm.org/
      is_external: true

    - title: Learn
      url: /learn/
      # Should link to training and getting started pages

    - title: Community
      sublinks:
      - title: Contact
        url: /community/
      - title: Get Involved
        url: /contribute/
      - title: Code of Conduct
        url: /code-of-conduct/
      - title: Roadmap
        url: /roadmap/
      - title: Open-Source Programs
        url: /open-source-programs/

    - title: About Us
      sublinks:
      - title: About PyBaMM
        url: /about/
      - title: Ionworks
        url: https://ionworks.com/
        is_external: true
      - title: PyBaMM on Twitter
        url: https://twitter.com/pybamm_/
        is_external: true
      - title: Governance
        url: /governance/
      - title: PyBaMM Teams
        url: /teams/

    - title: News
      url: /news/

    - title: Contribute
      url: /contribute/


  footer:
    logo: pybamm_logo_whitetext.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://twitter.com/pybamm_/
        icon: twitter

      - link: https://www.youtube.com/@pybamm_/
        icon: youtube

      - link: https://github.com/pybamm-team/
        icon: github

    quicklinks:
      column1:
        title: ""
        links:
          - text: Install PyBaMM
            link: https://docs.pybamm.org/en/stable/source/user_guide/installation/index.html

          - text: Getting started
            link: /learn/

          - text: Examples
            link: https://github.com/pybamm-team/PyBaMM/tree/develop/examples/

          - text: Documentation
            link: https://docs.pybamm.org/

          - text: Release notes
            link: /changelog/

      column2:
        title: ""
        links:
          - text: Contact
            link: /community/

          - text: Get involved
            link: /contribute/

          - text: Training
            link: /training/

          - text: Ionworks
            link: https://ionworks.com/

          - text: News
            link: /news/

      column3:
        title: ""
        links:
          - text: About PyBaMM
            link: /about/

          - text: Citing PyBaMM
            link: /publications/

          - text: Teams
            link: /teams/

          - text: Governance
            link: /governance/

          - text: Roadmap
            link: https://github.com/pybamm-team/PyBaMM/wiki/Roadmap/
